name: TownTeleport
version: @version@
main: net.azisaba.townteleport.TownTeleport
api-version: '1.21'
author: Azisaba Network
softdepend:
  - Townia
commands:
  townteleport:
    permission: townteleport.command
